### ISSUE TITLE
Не возникает сообщение об ошибке при нажатии на кнопку Войти и  Поля "Электронная почта", "Пароль" некорректно заполнены .

### ISSUE THREAD

**Issue by eiiao** [Githance/testing#10]
**Описание:**
Если  Поля "Электронная почта", "Пароль" некорректно заполнены  и нажать на кнопку Войти - не возникает сообщение об ошибке.

**Шаги воспроизведения:**
1.Открыть https://dev.githance.com/auth
2.Ввести в поле email  - ффф
3.Ввести в поле Пароль -1
4.Нажать на кнопку "Войти"

**Ожидаемый результат:**
Высвечивается сообщение об ошибке

**Фактический результат:**
Сообщение об ошибке не высвечивается

**Окружение:**
Windows 10 Pro, Chrome Версия 110.0.5481.180

**Comment by Ridmel** [comment]
Да, это не обрабатывается ответ. 

![image](https://user-images.githubusercontent.com/80767090/224518125-994d1273-c805-4f93-93d0-b9332aae743f.png)

**Comment by BKonstantine** [comment]
Закрыто 

* https://github.com/Githance/frontend/pull/66

**Comment by eiiao** [comment]
@BKonstantine , проверила, кейс исправлен.  Перевела в статус Fixed and Tested
