### ISSUE TITLE
При регистрации,  в поле Электронная почта, электронный адрес до @ c валидными символами, возвращается ошибка 500.

### ISSUE THREAD

**Issue by NataliVl** [Githance/testing#11]
### Описание:

При регистрации, если в адресе электронной почты до @ содержатся символы из группы % | / ! возвращается ошибка 500, страница Регистрации не сменяется на страницу Письмо отправлено, но данные пользователя появляются в административном стенде.

### Шаги вопроизведения:

1. Открыть страницу регистрации [https://dev.githance.com/auth/registration](url)
2. Ввести в поле Электронная почта nnn!@nnn.ru
3. Нажать кнопку Зарегистрироваться.
4. Проверить DevTools на возврат кода ошибки.
5. Проверить административный стенд [https://dev.githance.com/admin/users/user/](url), вкладку Пользователи, электронный адрес nnn!@nnn.ru

### Ожидаемый результат:

После нажатия на кнопку Зарегистрироваться, с данными в поле Электронная почта nnn!@nnn.ru, откроется страница -  Письмо отправлено, код 200, ошибок нет.

### Фактический результат:

После нажатия на кнопку Зарегистрироваться, с данными в поле Электронная почта nnn!@nnn.ru, страница Регистрации не меняется, не открывается страница Письмо отправлено, код ошибки 500.

### Окружение:

windows 7 х64, Яндекс.Браузер 22.11 разрешение экрана 1366x768, Chrome 107 разрешение экрана 1920x1080, Safari разрешение экрана 1536x864, Opera 1280x720

### Дополнительная информация:

![75 Рег Пароль проц симв нет рег есть в БД](https://user-images.githubusercontent.com/121474130/227681776-3ef4befe-6ada-4f30-82a7-45271ebf39a2.JPG)
![75 Рег Пароль проц симв нет рег есть в БД2](https://user-images.githubusercontent.com/121474130/227681785-3913bda1-1769-475a-ba43-04a10c55f8f7.JPG)
![88 Рег Пароль дробь симв нет рег есть в БД](https://user-images.githubusercontent.com/121474130/227681806-cce44169-4d4c-420b-a73b-2ac982e9796d.JPG)
![88 Рег Пароль дробь симв нет рег есть в БД2](https://user-images.githubusercontent.com/121474130/227681814-dbce4e59-2a8a-42c1-8c0c-00c615e12690.JPG)
![90 Рег Эл п воскл зн 500 есть в БД2](https://user-images.githubusercontent.com/121474130/227681840-fcaf3790-3740-493b-a1e5-f4e12c2f7423.JPG)

**Comment by Ridmel** [comment]
Оказывается, у SMTP сервера (сервер для отправки почты) beget'а, чьими услугами мы пользуемся, свой взгляд на допустимые символы. Написал в тех. поддержку, попросил предоставить список валидных символов для их сервера. Посмотрим, что ответят.

**Comment by Ridmel** [comment]
Ответ тех. поддержки:

> Добрый день!
> 
> Такс по данной ситуации уже имеется в нашей системе.
> 
> На текущий момент часть символов недоступна к использованию. К сожалению, точный список предоставить мы не сможем.

Только эти `% | / !` символы из валидных в джанге вызывали ошибку, остальные нормально?

**Comment by NataliVl** [comment]
До @ только эти символы

**Comment by Ridmel** [comment]
Исправлено в PR:
- https://github.com/Githance/backend/pull/39

**Comment by Ridmel** [comment]
@NataliVl Если задача завершена, ее надо закрыть.
