### ISSUE TITLE
При регистрации, в поле Электронная почта, в адрес электронной почты можно ввести общее количество символов превышающее допустимое количество, код 200

### ISSUE THREAD

**Issue by NataliVl** [Githance/testing#12]
### Описание:

При регистрации, если в поле Электронная почта,  в адрес электронной почты ввести общее количество символов более допустимого количества, то возвращается код 200, открывается страница Письмо отправлено, в административном стенде имя пользователя присутствует, но адрес электронной почты не отражается.

### Шаги вопроизведения:

1.Открыть страницу регистрации [https://dev.githance.com/auth/registration](https://github.com/Githance/testing/issues/url)
2. Ввести в поле Электронная почта 300 символов nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn@nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn.rurururururururururururururururururururururururu
3. Нажать кнопку Зарегистрироваться.
4. Проверить DevTools на возврат кода ошибки.
5. Проверить административный стенд [https://dev.githance.com/admin/users/user/](https://github.com/Githance/testing/issues/url), вкладку Пользователи, электронный адрес nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn@nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn.rurururururururururururururururururururururururu

### Ожидаемый результат:

При клике на кнопку Зарегистрироваться, если превышено допустимое количество введенных символов в поле Электронная почта, поле подсвечивается красным, код ошибки 400.

### Фактический результат:

При клике на кнопку Зарегистрироваться, если превышено допустимое количество введенных символов в поле Электронная почта, поле не подсвечивается красным, код 200, открывается страница Письмо отправлено.

### Окружение:

windows 7 х64, Яндекс.Браузер 22.11 разрешение экрана 1366x768, Chrome 107 разрешение экрана 1920x1080, Safari разрешение экрана 1536x864, Opera 1280x720

### Дополнительная информация:

![190 Рег Эл п превыш общего колво 255 зн2](https://user-images.githubusercontent.com/121474130/227689450-11e5bc30-24d2-4d08-8458-a12fbbdd0f48.JPG)
![190 Рег Эл п превыш общего колво 255 зн 3](https://user-images.githubusercontent.com/121474130/227689462-223bead9-3356-49bb-b38b-26a20d6c9dd4.JPG)
![192 Рег Эл п превыш общего колво 300 зн 3](https://user-images.githubusercontent.com/121474130/227689483-01394399-7563-42ba-a156-22feef7b01ca.JPG)
![193 Рег Эл п превыш общего колво 300 зн 2](https://user-images.githubusercontent.com/121474130/227689494-f420d6d1-0bb8-4925-8287-d92b43e76a58.JPG)

**Comment by Ridmel** [comment]
Я понял. Да, так можно создать одну запись в базе, потом будет 500 ошибка вываливаться. Исправлю.

**Comment by Ridmel** [comment]
Поменял важность бага с критического на обычный.

**Comment by Ridmel** [comment]
Исправлено в PR:
- https://github.com/Githance/backend/pull/39
