### ISSUE TITLE
На странице регистрации поле емайл не подсвечивается красным если вести больше 249 символов

### ISSUE THREAD

**Issue by oleg8s** [Githance/testing#13]
### Описание:

При регистрации, если в адресе почты до @ ввести символы длиной 250, 251, 300 возвращается ошибка 500, не подсвечивается красным, нет  сообщение "Введите правильный адрес электронной почты"

### Шаги вопроизведения:

1. Открыть страницу регистрации https://dev.githance.com/auth/registration
2. Ввести в поле емайл: nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn@n.ru
3. Нажать кнопку Зарегистрироваться.
4. Проверить DevTools на возврат кода ошибки.

### Ожидаемый результат:

Поле подсвечивается красным, появляется сообщение "Введите правильный адрес электронной почты"

### Фактический результат:

Поля емайл не подсвечивается красным, нет  появляется сообщение код ошибки 500.

### Окружение:

windows 10 х64, Яндекс.Браузер 22.11 разрешение экрана 1366x768, Chrome 107 разрешение экрана 1920x1080, Safari разрешение экрана 1536x864, Opera 1280x720

### Дополнительная информация:

![Chrome 1920x1080 - 58](https://user-images.githubusercontent.com/125849065/227841148-de9c8568-48cd-4658-8a70-f2c86a5d5c09.png)
![56 Рег Пароль 250 симв повт рег нет сообщен](https://user-images.githubusercontent.com/125849065/227841170-16b6938e-6e4f-4373-91ba-a387a6d3a3d6.JPG)

**Comment by Ridmel** [comment]
Дубликат.
- https://github.com/Githance/testing/issues/12

**Comment by Ridmel** [comment]
Исправлено в PR:
- https://github.com/Githance/backend/pull/39
