### ISSUE TITLE
При регистрации, в адресе почты ввести домен русского или иностранного алфавита проходит регистрация

### ISSUE THREAD

**Issue by oleg8s** [Githance/testing#14]
### Описание:

Можно зарегистрироваться с таким доменом nnn@nnn..нату  или  nnn@nnn.工程师

### Шаги вопроизведения:

1. Открыть страницу регистрации https://dev.githance.com/auth/registration
2. Ввести в поле емайл: nnn@nnn..нату 
3. Нажать кнопку Зарегистрироваться.

### Ожидаемый результат:

Поле подсвечивается красным, появляется сообщение "Введите правильный адрес электронной почты"

### Фактический результат:

Проходит регистрация открывается страница письмо отправлено, в админке есть запись

### Окружение:

windows 10 х64, Яндекс.Браузер 22.11 разрешение экрана 1366x768, Chrome 107 разрешение экрана 1920x1080, Safari разрешение экрана 1536x864, Opera 1280x720

**Comment by Ridmel** [comment]
Исправлено в PR:
- https://github.com/Githance/backend/pull/39

**Comment by NataliVl** [comment]
![Эл адрес после точки2](https://github.com/Githance/testing/assets/121474130/586b3311-2ec8-4703-a476-a5d235babee8)
![Эл адрес после точки](https://github.com/Githance/testing/assets/121474130/44b91c0e-16c2-4999-8f53-96e920346667)

**Comment by NataliVl** [comment]
Регистрация происходит, но после точки иностранный алфавит меняет символы.

**Comment by Ridmel** [comment]
Исправлено в PR:

- https://github.com/Githance/backend/pull/55
