### ISSUE TITLE
На странице регистрации поле "Электронная почта" проходит валидацию с буквами отличными от латиницы после символа @ и до точки

### ISSUE THREAD

**Issue by eiiao** [Githance/testing#15]
### Описание:

Регистрация проходит, если в поле "Электронная почта" на странице регистрации  указать в адресе электронной почты не латинские буквы справа после @ и до точки перед доменом.
Пример: nnn@ната.ru,  nnn@مولود.ru.
При этом в админке в адресе электронной почты вместо букв не латинского алфавита подставляется другая комбинация из букв латинского алфавита, символов и цифр - nnn@xn--80aa1bv.ru

### Шаги воспроизведения:

Открыть страницу регистрации https://dev.githance.com/auth/registration
Ввести в поле емайл: nnn@ната.ru
Нажать кнопку Зарегистрироваться.

### Ожидаемый результат:

Поле подсвечивается красным, появляется сообщение "Введите правильный адрес электронной почты"

### Фактический результат:

Проходит регистрация открывается страница письмо отправлено, в админке есть запись, при этом вместо букв не латинского алфавита поставляется другая комбинация из бук латинского алфавита, символов и цифр - nnn@xn--80aa1bv.ru

### Окружение:

windows 10 х64, Яндекс.Браузер 22.11 разрешение экрана 1366x768, Chrome 107 разрешение экрана 1920x1080, Safari разрешение экрана 1536x864, Opera 1280x720

### Дополнительная информация:

![Image](https://user-images.githubusercontent.com/46874130/228201020-60138ec7-afc3-4535-853d-285d2a174269.jpg)
![Image](https://user-images.githubusercontent.com/46874130/228201019-df9808e5-0eb5-41a5-8625-75be437b2c49.jpg)

**Comment by Ridmel** [comment]
@eiiao Скрины можно просто вставлять через Ctrl+V. 
Если хочется, чтобы они не загромождали репорт, то можно под под кат. 

<details>
  <summary>Скрины</summary>

![image](https://user-images.githubusercontent.com/80767090/228063912-5d5a1be5-ec8d-474f-955c-e3077456ae49.png)

</details>

Делается так:
````md
<details>
  <summary>Скрины</summary>

![image](https://user-images.githubusercontent.com/80767090/228063912-5d5a1be5-ec8d-474f-955c-e3077456ae49.png)

</details>
````

**Comment by Ridmel** [comment]
Дубликат: 
- https://github.com/Githance/testing/issues/14

**Comment by eiiao** [comment]
@Ridmel , Рома, привет! Спасибо за инструкцию про вставку скрин. Про дубликат не совсем так. В репорте Олега речь о проверке валидации домена электронной почты , т.е. символов в email после точки em@ail.**ru**, в данной проверке речь о валидации после знака @ и до точки em@**ail**.ru.

**Comment by Ridmel** [comment]
@eiiao Ясно. Просто с точки зрения бэкенда это один и тот же случай, только описанный разными словами. Поэтому я на самый последний повесил лейбел дубликат.

**Comment by eiiao** [comment]
> @eiiao Ясно. Просто с точки зрения бэкенда это один и тот же случай, только описанный разными словами. Поэтому я на самый последний повесил лейбел дубликат.
@Ridmel , поняла , спасибо!

**Comment by Ridmel** [comment]
Исправлено в PR:
- https://github.com/Githance/backend/pull/39

**Comment by eiiao** [comment]
@Ridmel , Рома, проверила регистрацию на двух адресах - nnn@натааа.ru и nnn123@مولود.ru , оба адреса прошли валидацию , в БД создалась запись. 

![Image](https://user-images.githubusercontent.com/46874130/228892003-7f6df008-aa1c-490b-acc2-b2ee5ae6d48b.jpg)

**Comment by Ridmel** [comment]
![image](https://user-images.githubusercontent.com/80767090/228969362-b75c9a29-d927-4573-9e7a-44bacda9b1f9.png)

В общем, это на стороне фронта, а точнее именно самого браузера, происходит. Браузер конвертирует части почты, в которых присутствуют не ASCII символы, в punycode. А предыдущим фиксом я закрыл валидацию на бэкенде всех символов, кроме ASCII, но так как он шлет шлет punycode, т.е. имена перекодированные в ASCII, то валидация проходила и пользователь создавался. Поправлю.

**Comment by Ridmel** [comment]
С 3 попытки. 
Исправлено в PR:
- https://github.com/Githance/backend/pull/44

**Comment by eiiao** [comment]
@Ridmel, починилось! Закрываю задачу
