### ISSUE TITLE
На странице регистрации текст кнопки регистрации "Войти" вместо "Зарегистрироваться"

### ISSUE THREAD

**Issue by eiiao** [Githance/testing#16]
### Описание:

На странице регистрации текст кнопки регистрации "Войти" вместо "Зарегистрироваться"

### Шаги вопроизведения:

1. Открыть https://dev.githance.com/auth/registration

### Ожидаемый результат:

На странице регистрации текст кнопки регистрации -  "Зарегистрироваться"

### Фактический результат:

На странице регистрации текст кнопки регистрации "Войти" вместо "Зарегистрироваться"

### Окружение:

Windows 10, Chrome 111.0 

### Дополнительная информация:

Скрин https://drive.google.com/file/d/1WJzZb-Ul-mXMj7uCGSk0E88PMFd3uM87/view

**Comment by BKonstantine** [comment]
Исправлено
* https://github.com/Githance/frontend/pull/74

**Comment by eiiao** [comment]
@BKonstantine, проверено, все ок. Закрываю задачу.
