### ISSUE TITLE
При регистрации в поле Пароль при вводе значения длиной 129 символов и больше регистрация возможна

### ISSUE THREAD

**Issue by ShadberryN** [Githance/testing#17]
### Описание:

При регистрации в поле Пароль при вводе значения длиной 129 символов и более регистрация возможна, не подсвечивается красным, нет сообщение "Введите корректный пароль"

### Шаги вопроизведения:

1. Открыть страницу регистрации https://dev.githance.com/auth/registration
2. Заполнить поля Имя и Email корректными значениями
3. Заполнить поле Пароль значением НатальяНатальяНатальяНатальяНатальяНатальяНатальяНатальяНатальяНатальяНатальяНатальяНатальяНатальяНатальяНатальяНатальяНатальяНаталья1234567
4. Отметить чек-бока Соглашения
5. Нажать кнопку Войти

### Ожидаемый результат:

Поле подсвечивается красным, появляется сообщение "Введите корректный пароль", регистрация невозможна

### Фактический результат:

Происходит регистрация нового пользователя, появляется окно "Письмо отправлено"

### Окружение:

windows 10 х64, Яндекс.Браузер 22.11 разрешение экрана 1366x768, Chrome 107 разрешение экрана 1920x1080, Safari разрешение экрана 1536x864, Opera 1280x720

### Дополнительная информация:

![Снимок экрана (131)](https://user-images.githubusercontent.com/126621584/228304218-738672dc-412c-4c76-86e4-042c749a678e.png)

**Comment by Ridmel** [comment]
Актуальная информация: пароль может быть любой длины, ограничений нет. Ограничение, озвученное ранее, в 128 символов относится не к паролю, а к хешу, который получается из этого пароля. Закрываю репорт.
