### ISSUE TITLE
При регистрации в поле Электронный адрес допускаются двойные кавычки

### ISSUE THREAD

**Issue by ShadberryN** [Githance/testing#18]
### Описание:

При регистрации в поле Электронный адрес, в части до знака @, допускаются двойные кавычки (недопустимый символ)

### Шаги вопроизведения:

1. Открыть страницу регистрации https://dev.githance.com/auth/registration
2. Ввести в поле Электронная почта "nnn"@nnn.ru
3. Заполнить поля Имя и Пароль  корректными значениями
4. Отметить чек-бокс Соглашения
5. Нажать кнопку Зарегистрироваться.

### Ожидаемый результат:

Регистрация не происходит, поле подсвечено красным, сообщение об ошибке "Введите правильный адрес электронной почты"

### Фактический результат:

Регистрация происходит, открывается страница Письмо отправлено. код 200, ошибок нет

### Окружение:

windows 10 х64, Яндекс.Браузер 22.11 разрешение экрана 1366x768, Chrome 107 разрешение экрана 1920x1080, Safari разрешение экрана 1536x864, Opera 1280x720

### Дополнительная информация:

![Снимок экрана (132)](https://user-images.githubusercontent.com/126621584/228353041-cdff0fce-79dc-470c-96dc-6c560b0ef2e4.png)

**Comment by Ridmel** [comment]
Исправлено в PR:
- https://github.com/Githance/backend/pull/40
