### ISSUE TITLE
В форме входа существующего пользователя поле Пароль валидируется при вводе менее 8 символов

### ISSUE THREAD

**Issue by eiiao** [Githance/testing#8]
### Описание:

В форме входа существующего пользователя при вводе значений пароля менее 8 символов, поля подсвечиваются зеленым, не возникает ошибки о том, что пароль должен быть 8и более символов

### Шаги воспроизведения:

1.  Открыть https://dev.githance.com/auth
2.  Ввести в поле пароль - 111
3.  Перевести фокус с поля пароль

### Ожидаемый результат:

При вводе значений менее 8 символов, поле подсвечивается красным , появляется сообщение об ошибке

### Фактический результат:

При вводе значений менее 8  символов, поле подсвечивается зеленым и не появляется сообщение об ошибке

### Окружение:

Windows 10 Pro, Chrome Версия 110.0.5481.180

### Дополнительная информация:

![user auth form - email password validation err](https://user-images.githubusercontent.com/46874130/224513248-f584bee1-205b-4d83-8ebc-ddfbc4392eb0.jpg)

**Comment by Ridmel** [comment]
Валидация происходит только при регистрации. Это правильное поведение. 
Я бы даже убрал надпись `заполни меня`, тем более красным цветом, когда снимаешь фокус, а поле ввода пустое. Достаточно неактивной кнопки `Войти` как индикатор. Плюс я бы еще убрал зеленый цвет самой рамки, поскольку непонятно, для чего он меняется, ведь валидации нет.

**Comment by BKonstantine** [comment]
В форме авторизации проверяется только наличие данных в полях ввода. Вся проверка осуществляется на бэке.

**Comment by eiiao** [comment]
@BKonstantine,  окей поняла. Закрываю кейс?

**Comment by BKonstantine** [comment]
@eiiao Думаю да, т.к это точно не является ошибкой. А на счет поведения интерфейса, с Настей проговорю.
