### ISSUE TITLE
В форме входа существующего пользователя поля "Электронная почта",  "Пароль" не выдерживают переполнение контента

### ISSUE THREAD

**Issue by eiiao** [Githance/testing#9]
**Описание:**
В форме входа существующего пользователя поля Электронная почта,  Пароль не выдерживают переполнение контента

**Шаги воспроизведения:**
1.Открыть https://dev.githance.com/auth
2.Ввести в поле email  - 1111111111111111111111111111111111111111111@yandex.ru
3.Ввести в поле Пароль - 111111111111111111111111111111111111111111111111111111111

**Ожидаемый результат:**
Поле email вмещает в себя все введённые символы
Поле пароль вмещает в себя все введённые символы

**Фактический результат:**
Поле email не вмещает в себя все введённые символы, введённый email выходит за границы поля
Поле пароль не вмещает в себя все введённые символы, введённый пароль выходит за границы поля

**Окружение:**
Windows 10 Pro, Chrome Версия 110.0.5481.180 
![Image](https://user-images.githubusercontent.com/46874130/224514894-5ba2b6b1-387d-42d0-90d3-f5430b529b39.jpg)

**Comment by BKonstantine** [comment]
@eiiao Вопрос. Почему поля ввода должны показывать все введенные символы?

**Comment by eiiao** [comment]
> Вопрос. Почему поля ввода должны показывать все введенные символы?
@BKonstantine , ты прав, наверное , я неверно завела это как баг. Это скорее фича на усмотрение разработчиком и ПМ. :) Но еще при переполнении контента в поле Пароль - значок глаза открытого/закрытого накладывается на введенные в поле данные  .

**Comment by BKonstantine** [comment]
@eiiao А наплыв текста и значка, мы поправим. Ваня этим занимается.

**Comment by BKonstantine** [comment]
Закрыто 

* https://github.com/Githance/frontend/pull/66

**Comment by Ridmel** [comment]
> Закрыто

@BKonstantine  Давай какое-нибудь другое слово/описание использовать, вместо "Закрыто", когда сообщаешь, что исправил эту ошибку на фронте. Т.к. эту issue еще не протестировали и не закрыли, а слово вводит в заблуждение.

**Comment by eiiao** [comment]
@foxriver660 , @BKonstantine , проверила, кейс исправлен :) Статус поменяла на Fixed and Tested

**Comment by Ridmel** [comment]
@eiiao тогда закрывай таску, а она уже сама переместится в последнюю колонку на доске.

**Comment by eiiao** [comment]
@Ridmel, почему-то нельзя поменять задачу с Open на Closed, при нажатии на Open нет возможности перевести задачу в Closed. Может потому , что я сначала статус поменяла на Fixed and Tested, а потом пытаюсь закрыть?

**Comment by Ridmel** [comment]
@eiiao повысил права. Сейчас появилась такая возможность?

**Comment by eiiao** [comment]
@Ridmel , неа :( Кнопка Open не кликабельна

**Comment by Ridmel** [comment]
@eiiao 
Почему кнопка Open? Внизу кнопка Close.
![image](https://user-images.githubusercontent.com/80767090/229106038-f9f9b096-28d3-4494-996c-0965516f405a.png)

**Comment by eiiao** [comment]
@Ridmel, затупила, но теперь разобралась) спасибо!
